spring:
  application:
    name: springcloud-eureka-server
server:
  #含义：读取系统可以端口，否则使用定义
  port: 8080
#设置该服务中心的hostname，指定ip,该实例名称不能重复
eureka:
  instance:
    hostname: 172.16.76.3
  client:
    #是否注册自己，默认true，这个应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种自己向自己注册的默认行为
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false。
    fetch-registry: false
    #指定服务注册中心的位置
    #如果是集群，Eureka集群相互指向注册中心
    service-url:
      # 此写法 需要在 VM options 中定于配置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #自我保护模式默认是自动开启的，可以选择关闭，禁用自我保护模式,保证不可用的服务及时剔除
    enable-self-preservation: false
    #剔除失效服务间隔单位ms，默认60s
    eviction-interval-timer-in-ms: 20000
    #留存的服务示例低于多少比例进入保护模式，默认85%
    renewal-percent-threshold: 0.5